/**
 * Philippine Address Data for Cascading Dropdowns
 * Structure: Region → Province → City/Municipality
 * Barangay is left as free text input due to volume
 */

export interface AddressOption {
  label: string;
  value: string;
}

export interface PhilippineAddressData {
  [region: string]: {
    [province: string]: string[];
  };
}

export const philippineAddress: PhilippineAddressData = {
  NCR: {
    "Metro Manila": [
      "Caloocan",
      "Las Piñas",
      "Makati",
      "Malabon",
      "Mandaluyong",
      "Manila",
      "Marikina",
      "Muntinlupa",
      "Navotas",
      "Parañaque",
      "Pasay",
      "Pasig",
      "Pateros",
      "Quezon City",
      "San Juan",
      "Taguig",
      "Valenzuela",
    ],
  },
  CAR: {
    Abra: [
      "Bangued",
      "Boliney",
      "Bucay",
      "Bucloc",
      "Daguioman",
      "Danglas",
      "Dolores",
      "La Paz",
      "Lacub",
      "Lagangilang",
      "Lagayan",
      "Langiden",
      "Licuan-Baay",
      "Luba",
      "Malibcong",
      "Manabo",
      "Peñarrubia",
      "Pidigan",
      "Pilar",
      "Sallapadan",
      "San Isidro",
      "San Juan",
      "San Quintin",
      "Tayum",
      "Tineg",
      "Tubo",
      "Villaviciosa",
    ],
    Apayao: [
      "Calanasan",
      "Conner",
      "Flora",
      "Kabugao",
      "Luna",
      "Pudtol",
      "Santa Marcela",
    ],
    Benguet: [
      "Baguio City",
      "Atok",
      "Bakun",
      "Bokod",
      "Buguias",
      "Itogon",
      "Kabayan",
      "Kapangan",
      "Kibungan",
      "La Trinidad",
      "Mankayan",
      "Sablan",
      "Tuba",
      "Tublay",
    ],
    Ifugao: [
      "Aguinaldo",
      "Alfonso Lista",
      "Asipulo",
      "Banaue",
      "Hingyon",
      "Hungduan",
      "Kiangan",
      "Lagawe",
      "Lamut",
      "Mayoyao",
      "Tinoc",
    ],
    Kalinga: [
      "Balbalan",
      "Lubuagan",
      "Pasil",
      "Pinukpuk",
      "Rizal",
      "Tabuk City",
      "Tanudan",
      "Tinglayan",
    ],
    "Mountain Province": [
      "Barlig",
      "Bauko",
      "Besao",
      "Bontoc",
      "Natonin",
      "Paracelis",
      "Sabangan",
      "Sadanga",
      "Sagada",
      "Tadian",
    ],
  },
  "Region I": {
    "Ilocos Norte": [
      "Laoag City",
      "Batac City",
      "Adams",
      "Bacarra",
      "Badoc",
      "Bangui",
      "Banna",
      "Burgos",
      "Carasi",
      "Currimao",
      "Dingras",
      "Dumalneg",
      "Marcos",
      "Nueva Era",
      "Pagudpud",
      "Paoay",
      "Pasuquin",
      "Piddig",
      "Pinili",
      "San Nicolas",
      "Sarrat",
      "Solsona",
      "Vintar",
    ],
    "Ilocos Sur": [
      "Vigan City",
      "Candon City",
      "Alilem",
      "Banayoyo",
      "Bantay",
      "Burgos",
      "Cabugao",
      "Caoayan",
      "Cervantes",
      "Galimuyod",
      "Gregorio del Pilar",
      "Lidlidda",
      "Magsingal",
      "Nagbukel",
      "Narvacan",
      "Quirino",
      "Salcedo",
      "San Emilio",
      "San Esteban",
      "San Ildefonso",
      "San Juan",
      "San Vicente",
      "Santa",
      "Santa Catalina",
      "Santa Cruz",
      "Santa Lucia",
      "Santa Maria",
      "Santiago",
      "Santo Domingo",
      "Sigay",
      "Sinait",
      "Sugpon",
      "Suyo",
      "Tagudin",
    ],
    "La Union": [
      "San Fernando City",
      "Agoo",
      "Aringay",
      "Bacnotan",
      "Bagulin",
      "Balaoan",
      "Bangar",
      "Bauang",
      "Burgos",
      "Caba",
      "Luna",
      "Naguilian",
      "Pugo",
      "Rosario",
      "San Gabriel",
      "San Juan",
      "Santo Tomas",
      "Santol",
      "Sudipen",
      "Tubao",
    ],
    Pangasinan: [
      "Dagupan City",
      "Alaminos City",
      "San Carlos City",
      "Urdaneta City",
      "Agno",
      "Aguilar",
      "Alcala",
      "Anda",
      "Asingan",
      "Balungao",
      "Bani",
      "Basista",
      "Bautista",
      "Bayambang",
      "Binalonan",
      "Binmaley",
      "Bolinao",
      "Bugallon",
      "Burgos",
      "Calasiao",
      "Dasol",
      "Infanta",
      "Labrador",
      "Laoac",
      "Lingayen",
      "Mabini",
      "Malasiqui",
      "Manaoag",
      "Mangaldan",
      "Mangatarem",
      "Mapandan",
      "Natividad",
      "Pozorrubio",
      "Rosales",
      "San Fabian",
      "San Jacinto",
      "San Manuel",
      "San Nicolas",
      "San Quintin",
      "Santa Barbara",
      "Santa Maria",
      "Santo Tomas",
      "Sison",
      "Sual",
      "Tayug",
      "Umingan",
      "Urbiztondo",
      "Villasis",
    ],
  },
  "Region II": {
    Batanes: ["Basco", "Itbayat", "Ivana", "Mahatao", "Sabtang", "Uyugan"],
    Cagayan: [
      "Tuguegarao City",
      "Abulug",
      "Alcala",
      "Allacapan",
      "Amulung",
      "Aparri",
      "Baggao",
      "Ballesteros",
      "Buguey",
      "Calayan",
      "Camalaniugan",
      "Claveria",
      "Enrile",
      "Gattaran",
      "Gonzaga",
      "Iguig",
      "Lal-lo",
      "Lasam",
      "Pamplona",
      "Peñablanca",
      "Piat",
      "Rizal",
      "Sanchez-Mira",
      "Santa Ana",
      "Santa Praxedes",
      "Santa Teresita",
      "Santo Niño",
      "Solana",
      "Tuao",
    ],
    Isabela: [
      "Ilagan City",
      "Cauayan City",
      "Santiago City",
      "Alicia",
      "Angadanan",
      "Aurora",
      "Benito Soliven",
      "Burgos",
      "Cabagan",
      "Cabatuan",
      "Cordon",
      "Delfin Albano",
      "Dinapigue",
      "Divilacan",
      "Echague",
      "Gamu",
      "Jones",
      "Luna",
      "Maconacon",
      "Mallig",
      "Naguilian",
      "Palanan",
      "Quezon",
      "Quirino",
      "Ramon",
      "Reina Mercedes",
      "Roxas",
      "San Agustin",
      "San Guillermo",
      "San Isidro",
      "San Manuel",
      "San Mariano",
      "San Mateo",
      "San Pablo",
      "Santa Maria",
      "Santo Tomas",
      "Tumauini",
    ],
    "Nueva Vizcaya": [
      "Bayombong",
      "Solano",
      "Alfonso Castañeda",
      "Ambaguio",
      "Aritao",
      "Bagabag",
      "Bambang",
      "Diadi",
      "Dupax del Norte",
      "Dupax del Sur",
      "Kasibu",
      "Kayapa",
      "Quezon",
      "Santa Fe",
      "Villaverde",
    ],
    Quirino: [
      "Cabarroguis",
      "Aglipay",
      "Diffun",
      "Maddela",
      "Nagtipunan",
      "Saguday",
    ],
  },
  "Region III": {
    Aurora: [
      "Baler",
      "Casiguran",
      "Dilasag",
      "Dinalungan",
      "Dingalan",
      "Dipaculao",
      "Maria Aurora",
      "San Luis",
    ],
    Bataan: [
      "Balanga City",
      "Abucay",
      "Bagac",
      "Dinalupihan",
      "Hermosa",
      "Limay",
      "Mariveles",
      "Morong",
      "Orani",
      "Orion",
      "Pilar",
      "Samal",
    ],
    Bulacan: [
      "Malolos City",
      "Meycauayan City",
      "San Jose del Monte City",
      "Angat",
      "Balagtas",
      "Baliuag",
      "Bocaue",
      "Bulakan",
      "Bustos",
      "Calumpit",
      "Doña Remedios Trinidad",
      "Guiguinto",
      "Hagonoy",
      "Marilao",
      "Norzagaray",
      "Obando",
      "Pandi",
      "Paombong",
      "Plaridel",
      "Pulilan",
      "San Ildefonso",
      "San Miguel",
      "San Rafael",
      "Santa Maria",
    ],
    "Nueva Ecija": [
      "Cabanatuan City",
      "Gapan City",
      "Palayan City",
      "San Jose City",
      "Aliaga",
      "Bongabon",
      "Cabiao",
      "Carranglan",
      "Cuyapo",
      "Gabaldon",
      "General Mamerto Natividad",
      "General Tinio",
      "Guimba",
      "Jaen",
      "Laur",
      "Licab",
      "Llanera",
      "Lupao",
      "Nampicuan",
      "Pantabangan",
      "Peñaranda",
      "Quezon",
      "Rizal",
      "San Antonio",
      "San Isidro",
      "San Leonardo",
      "Santa Rosa",
      "Santo Domingo",
      "Talavera",
      "Talugtug",
      "Zaragoza",
    ],
    Pampanga: [
      "San Fernando City",
      "Angeles City",
      "Apalit",
      "Arayat",
      "Bacolor",
      "Candaba",
      "Floridablanca",
      "Guagua",
      "Lubao",
      "Mabalacat City",
      "Macabebe",
      "Magalang",
      "Masantol",
      "Mexico",
      "Minalin",
      "Porac",
      "San Luis",
      "San Simon",
      "Santa Ana",
      "Santa Rita",
      "Santo Tomas",
      "Sasmuan",
    ],
    Tarlac: [
      "Tarlac City",
      "Anao",
      "Bamban",
      "Camiling",
      "Capas",
      "Concepcion",
      "Gerona",
      "La Paz",
      "Mayantoc",
      "Moncada",
      "Paniqui",
      "Pura",
      "Ramos",
      "San Clemente",
      "San Jose",
      "San Manuel",
      "Santa Ignacia",
      "Victoria",
    ],
    Zambales: [
      "Olongapo City",
      "Botolan",
      "Cabangan",
      "Candelaria",
      "Castillejos",
      "Iba",
      "Masinloc",
      "Palauig",
      "San Antonio",
      "San Felipe",
      "San Marcelino",
      "San Narciso",
      "Santa Cruz",
      "Subic",
    ],
  },
  "Region IV-A": {
    Batangas: [
      "Batangas City",
      "Lipa City",
      "Tanauan City",
      "Santo Tomas City",
      "Agoncillo",
      "Alitagtag",
      "Balayan",
      "Balete",
      "Bauan",
      "Calaca",
      "Calatagan",
      "Cuenca",
      "Ibaan",
      "Laurel",
      "Lemery",
      "Lian",
      "Lobo",
      "Mabini",
      "Malvar",
      "Mataas na Kahoy",
      "Nasugbu",
      "Padre Garcia",
      "Rosario",
      "San Jose",
      "San Juan",
      "San Luis",
      "San Nicolas",
      "San Pascual",
      "Santa Teresita",
      "Taal",
      "Taysan",
      "Tingloy",
      "Tuy",
    ],
    Cavite: [
      "Cavite City",
      "Tagaytay City",
      "Trece Martires City",
      "Dasmariñas City",
      "Bacoor City",
      "Imus City",
      "General Trias City",
      "Alfonso",
      "Amadeo",
      "Carmona",
      "Gen. Mariano Alvarez",
      "Indang",
      "Kawit",
      "Magallanes",
      "Maragondon",
      "Mendez",
      "Naic",
      "Noveleta",
      "Rosario",
      "Silang",
      "Tanza",
      "Ternate",
    ],
    Laguna: [
      "Santa Cruz",
      "Calamba City",
      "San Pablo City",
      "Biñan City",
      "Cabuyao City",
      "San Pedro City",
      "Santa Rosa City",
      "Alaminos",
      "Bay",
      "Calauan",
      "Cavinti",
      "Famy",
      "Kalayaan",
      "Liliw",
      "Los Baños",
      "Luisiana",
      "Lumban",
      "Mabitac",
      "Magdalena",
      "Majayjay",
      "Nagcarlan",
      "Paete",
      "Pagsanjan",
      "Pakil",
      "Pangil",
      "Pila",
      "Rizal",
      "Siniloan",
      "Victoria",
    ],
    Quezon: [
      "Lucena City",
      "Tayabas City",
      "Agdangan",
      "Alabat",
      "Atimonan",
      "Buenavista",
      "Burdeos",
      "Calauag",
      "Candelaria",
      "Catanauan",
      "Dolores",
      "General Luna",
      "General Nakar",
      "Guinayangan",
      "Gumaca",
      "Infanta",
      "Jomalig",
      "Lopez",
      "Lucban",
      "Macalelon",
      "Mauban",
      "Mulanay",
      "Padre Burgos",
      "Pagbilao",
      "Panukulan",
      "Patnanungan",
      "Perez",
      "Pitogo",
      "Plaridel",
      "Polillo",
      "Quezon",
      "Real",
      "Sampaloc",
      "San Andres",
      "San Antonio",
      "San Francisco",
      "San Narciso",
      "Sariaya",
      "Tagkawayan",
      "Tiaong",
      "Unisan",
    ],
    Rizal: [
      "Antipolo City",
      "Angono",
      "Baras",
      "Binangonan",
      "Cainta",
      "Cardona",
      "Jalajala",
      "Morong",
      "Pililla",
      "Rodriguez",
      "San Mateo",
      "Tanay",
      "Taytay",
      "Teresa",
    ],
  },
  "Region IV-B": {
    Marinduque: [
      "Boac",
      "Buenavista",
      "Gasan",
      "Mogpog",
      "Santa Cruz",
      "Torrijos",
    ],
    "Occidental Mindoro": [
      "Mamburao",
      "Abra de Ilog",
      "Calintaan",
      "Looc",
      "Lubang",
      "Magsaysay",
      "Paluan",
      "Rizal",
      "Sablayan",
      "San Jose",
      "Santa Cruz",
    ],
    "Oriental Mindoro": [
      "Calapan City",
      "Baco",
      "Bansud",
      "Bongabong",
      "Bulalacao",
      "Gloria",
      "Mansalay",
      "Naujan",
      "Pinamalayan",
      "Pola",
      "Puerto Galera",
      "Roxas",
      "San Teodoro",
      "Socorro",
      "Victoria",
    ],
    Palawan: [
      "Puerto Princesa City",
      "Aborlan",
      "Agutaya",
      "Araceli",
      "Balabac",
      "Bataraza",
      "Brooke's Point",
      "Busuanga",
      "Cagayancillo",
      "Coron",
      "Culion",
      "Cuyo",
      "Dumaran",
      "El Nido",
      "Kalayaan",
      "Linapacan",
      "Magsaysay",
      "Narra",
      "Quezon",
      "Rizal",
      "Roxas",
      "San Vicente",
      "Sofronio Española",
      "Taytay",
    ],
    Romblon: [
      "Romblon",
      "Alcantara",
      "Banton",
      "Cajidiocan",
      "Calatrava",
      "Concepcion",
      "Corcuera",
      "Ferrol",
      "Looc",
      "Magdiwang",
      "Odiongan",
      "San Agustin",
      "San Andres",
      "San Fernando",
      "San Jose",
      "Santa Fe",
      "Santa Maria",
    ],
  },
  "Region V": {
    Albay: [
      "Legazpi City",
      "Ligao City",
      "Tabaco City",
      "Bacacay",
      "Camalig",
      "Daraga",
      "Guinobatan",
      "Jovellar",
      "Libon",
      "Malilipot",
      "Malinao",
      "Manito",
      "Oas",
      "Pio Duran",
      "Polangui",
      "Rapu-Rapu",
      "Santo Domingo",
      "Tiwi",
    ],
    "Camarines Norte": [
      "Daet",
      "Basud",
      "Capalonga",
      "Jose Panganiban",
      "Labo",
      "Mercedes",
      "Paracale",
      "San Lorenzo Ruiz",
      "San Vicente",
      "Santa Elena",
      "Talisay",
      "Vinzons",
    ],
    "Camarines Sur": [
      "Naga City",
      "Iriga City",
      "Baao",
      "Balatan",
      "Bato",
      "Bombon",
      "Buhi",
      "Bula",
      "Cabusao",
      "Calabanga",
      "Camaligan",
      "Canaman",
      "Caramoan",
      "Del Gallego",
      "Gainza",
      "Garchitorena",
      "Goa",
      "Lagonoy",
      "Libmanan",
      "Lupi",
      "Magarao",
      "Milaor",
      "Minalabac",
      "Nabua",
      "Ocampo",
      "Pamplona",
      "Pasacao",
      "Pili",
      "Presentacion",
      "Ragay",
      "Sagñay",
      "San Fernando",
      "San Jose",
      "Sipocot",
      "Siruma",
      "Tigaon",
      "Tinambac",
    ],
    Catanduanes: [
      "Virac",
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoran",
      "Gigmoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
    ],
    Masbate: [
      "Masbate City",
      "Aroroy",
      "Baleno",
      "Balud",
      "Batuan",
      "Cataingan",
      "Cawayan",
      "Claveria",
      "Dimasalang",
      "Esperanza",
      "Mandaon",
      "Milagros",
      "Mobo",
      "Monreal",
      "Palanas",
      "Pio V. Corpuz",
      "Placer",
      "San Fernando",
      "San Jacinto",
      "San Pascual",
      "Uson",
    ],
    Sorsogon: [
      "Sorsogon City",
      "Barcelona",
      "Bulan",
      "Bulusan",
      "Casiguran",
      "Castilla",
      "Donsol",
      "Gubat",
      "Irosin",
      "Juban",
      "Magallanes",
      "Matnog",
      "Pilar",
      "Prieto Diaz",
      "Santa Magdalena",
    ],
  },
  "Region VI": {
    Aklan: [
      "Kalibo",
      "Altavas",
      "Balete",
      "Banga",
      "Batan",
      "Buruanga",
      "Ibajay",
      "Lezo",
      "Libacao",
      "Madalag",
      "Makato",
      "Malay",
      "Malinao",
      "Nabas",
      "New Washington",
      "Numancia",
      "Tangalan",
    ],
    Antique: [
      "San Jose de Buenavista",
      "Anini-y",
      "Barbaza",
      "Belison",
      "Bugasong",
      "Caluya",
      "Culasi",
      "Dao",
      "Hamtic",
      "Laua-an",
      "Libertad",
      "Pandan",
      "Patnongon",
      "San Remigio",
      "Sebaste",
      "Sibalom",
      "Tibiao",
      "Tobias Fornier",
      "Valderrama",
    ],
    Capiz: [
      "Roxas City",
      "Cuartero",
      "Dao",
      "Dumalag",
      "Dumarao",
      "Ivisan",
      "Jamindan",
      "Ma-ayon",
      "Mambusao",
      "Panay",
      "Panitan",
      "Pilar",
      "Pontevedra",
      "President Roxas",
      "Sapian",
      "Sigma",
      "Tapaz",
    ],
    Guimaras: [
      "Jordan",
      "Buenavista",
      "Nueva Valencia",
      "San Lorenzo",
      "Sibunag",
    ],
    Iloilo: [
      "Iloilo City",
      "Passi City",
      "Ajuy",
      "Alimodian",
      "Anilao",
      "Badiangan",
      "Balasan",
      "Banate",
      "Barotac Nuevo",
      "Barotac Viejo",
      "Batad",
      "Bingawan",
      "Cabatuan",
      "Calinog",
      "Carles",
      "Concepcion",
      "Dingle",
      "Dueñas",
      "Dumangas",
      "Estancia",
      "Guimbal",
      "Igbaras",
      "Janiuay",
      "Lambunao",
      "Leganes",
      "Lemery",
      "Leon",
      "Maasin",
      "Miagao",
      "Mina",
      "New Lucena",
      "Oton",
      "Pavia",
      "Pototan",
      "San Dionisio",
      "San Enrique",
      "San Joaquin",
      "San Miguel",
      "San Rafael",
      "Santa Barbara",
      "Sara",
      "Tigbauan",
      "Tubungan",
      "Zarraga",
    ],
    "Negros Occidental": [
      "Bacolod City",
      "Bago City",
      "Cadiz City",
      "Escalante City",
      "Himamaylan City",
      "Kabankalan City",
      "La Carlota City",
      "Sagay City",
      "San Carlos City",
      "Silay City",
      "Sipalay City",
      "Talisay City",
      "Victorias City",
      "Binalbagan",
      "Calatrava",
      "Candoni",
      "Cauayan",
      "Don Salvador Benedicto",
      "Enrique B. Magalona",
      "Hinigaran",
      "Hinoba-an",
      "Ilog",
      "Isabela",
      "La Castellana",
      "Manapla",
      "Moises Padilla",
      "Murcia",
      "Paragas",
      "Pontevedra",
      "Pulupandan",
      "Salvador Benedicto",
      "San Enrique",
      "Toboso",
      "Valladolid",
    ],
  },
  "Region VII": {
    Bohol: [
      "Tagbilaran City",
      "Alburquerque",
      "Alicia",
      "Anda",
      "Antequera",
      "Baclayon",
      "Balilihan",
      "Batuan",
      "Bien Unido",
      "Bilar",
      "Buenavista",
      "Calape",
      "Candijay",
      "Carmen",
      "Catigbian",
      "Clarin",
      "Corella",
      "Cortes",
      "Dagohoy",
      "Danao",
      "Dauis",
      "Dimiao",
      "Duero",
      "Garcia Hernandez",
      "Guindulman",
      "Inabanga",
      "Jagna",
      "Lila",
      "Loay",
      "Loboc",
      "Loon",
      "Mabini",
      "Maribojoc",
      "Panglao",
      "Pilar",
      "President Carlos P. Garcia",
      "Sagbayan",
      "San Isidro",
      "San Miguel",
      "Sevilla",
      "Sierra Bullones",
      "Sikatuna",
      "Talibon",
      "Trinidad",
      "Tubigon",
      "Ubay",
      "Valencia",
    ],
    Cebu: [
      "Cebu City",
      "Mandaue City",
      "Lapu-Lapu City",
      "Talisay City",
      "Naga City",
      "Carcar City",
      "Danao City",
      "Toledo City",
      "Bogo City",
      "Alcantara",
      "Alcoy",
      "Alegria",
      "Aloguinsan",
      "Argao",
      "Asturias",
      "Badian",
      "Balamban",
      "Bantayan",
      "Barili",
      "Boljoon",
      "Borbon",
      "Carmen",
      "Catmon",
      "Compostela",
      "Consolacion",
      "Cordova",
      "Daanbantayan",
      "Dalaguete",
      "Dumanjug",
      "Ginatilan",
      "Liloan",
      "Madridejos",
      "Malabuyoc",
      "Medellin",
      "Minglanilla",
      "Moalboal",
      "Oslob",
      "Pilar",
      "Pinamungajan",
      "Poro",
      "Ronda",
      "Samboan",
      "San Fernando",
      "San Francisco",
      "San Remigio",
      "Santa Fe",
      "Santander",
      "Sibonga",
      "Sogod",
      "Tabogon",
      "Tabuelan",
      "Tuburan",
      "Tudela",
    ],
    "Negros Oriental": [
      "Dumaguete City",
      "Bayawan City",
      "Canlaon City",
      "Guihulngan City",
      "Tanjay City",
      "Amlan",
      "Ayungon",
      "Bacong",
      "Basay",
      "Bindoy",
      "Dauin",
      "Jimalalud",
      "La Libertad",
      "Mabinay",
      "Manjuyod",
      "Pamplona",
      "San Jose",
      "Santa Catalina",
      "Siaton",
      "Sibulan",
      "Tayasan",
      "Valencia",
      "Vallehermoso",
      "Zamboanguita",
    ],
    Siquijor: [
      "Siquijor",
      "Enrique Villanueva",
      "Larena",
      "Lazi",
      "Maria",
      "San Juan",
    ],
  },
  "Region VIII": {
    Biliran: [
      "Naval",
      "Almeria",
      "Biliran",
      "Cabucgayan",
      "Caibiran",
      "Culaba",
      "Kawayan",
      "Maripipi",
    ],
    "Eastern Samar": [
      "Borongan City",
      "Arteche",
      "Balangiga",
      "Balangkayan",
      "Can-avid",
      "Dolores",
      "General MacArthur",
      "Giporlos",
      "Guiuan",
      "Hernani",
      "Jipapad",
      "Lawaan",
      "Llorente",
      "Maslog",
      "Maydolong",
      "Mercedes",
      "Oras",
      "Quinapondan",
      "Salcedo",
      "San Julian",
      "San Policarpo",
      "Sulat",
      "Taft",
    ],
    Leyte: [
      "Tacloban City",
      "Ormoc City",
      "Abuyog",
      "Alangalang",
      "Albuera",
      "Babatngon",
      "Barugo",
      "Bato",
      "Baybay City",
      "Burauen",
      "Calubian",
      "Capoocan",
      "Carigara",
      "Dagami",
      "Dulag",
      "Hilongos",
      "Hindang",
      "Inopacan",
      "Isabel",
      "Jaro",
      "Javier",
      "Julita",
      "Kananga",
      "La Paz",
      "Leyte",
      "MacArthur",
      "Mahaplag",
      "Matag-ob",
      "Matalom",
      "Mayorga",
      "Merida",
      "Palo",
      "Palompon",
      "Pastrana",
      "San Isidro",
      "San Miguel",
      "Santa Fe",
      "Tabango",
      "Tabontabon",
      "Tanauan",
      "Tolosa",
      "Tunga",
      "Villaba",
    ],
    "Northern Samar": [
      "Catarman",
      "Allen",
      "Biri",
      "Bobon",
      "Capul",
      "Catubig",
      "Gamay",
      "Laoang",
      "Lapinig",
      "Las Navas",
      "Lavezares",
      "Lope de Vega",
      "Mapanas",
      "Mondragon",
      "Palapag",
      "Pambujan",
      "Rosario",
      "San Antonio",
      "San Isidro",
      "San Jose",
      "San Roque",
      "San Vicente",
      "Silvino Lobos",
      "Victoria",
    ],
    Samar: [
      "Catbalogan City",
      "Calbayog City",
      "Almagro",
      "Basey",
      "Calbiga",
      "Daram",
      "Gandara",
      "Hinabangan",
      "Jiabong",
      "Marabut",
      "Matuguinao",
      "Motiong",
      "Pagsanghan",
      "Paranas",
      "Pinabacdao",
      "San Jorge",
      "San Jose de Buan",
      "San Sebastian",
      "Santa Margarita",
      "Santa Rita",
      "Santo Niño",
      "Tagapul-an",
      "Talalora",
      "Tarangnan",
      "Villareal",
      "Wright",
      "Zumarraga",
    ],
    "Southern Leyte": [
      "Maasin City",
      "Anahawan",
      "Bontoc",
      "Hinunangan",
      "Hinundayan",
      "Libagon",
      "Liloan",
      "Limasawa",
      "Macrohon",
      "Malitbog",
      "Padre Burgos",
      "Pintuyan",
      "Saint Bernard",
      "San Francisco",
      "San Juan",
      "San Ricardo",
      "Silago",
      "Sogod",
      "Tomas Oppus",
    ],
  },
  "Region IX": {
    "Zamboanga del Norte": [
      "Dipolog City",
      "Dapitan City",
      "Bacungan",
      "Baliguian",
      "Godod",
      "Gutalac",
      "Jose Dalman",
      "Kalawit",
      "Katipunan",
      "La Libertad",
      "Labason",
      "Leon B. Postigo",
      "Liloy",
      "Manukan",
      "Mutia",
      "Piñan",
      "Polanco",
      "President Manuel A. Roxas",
      "Rizal",
      "Salug",
      "Sergio Osmeña Sr.",
      "Siayan",
      "Sibuco",
      "Sibutad",
      "Sindangan",
      "Siocon",
      "Sirawai",
      "Tampilisan",
    ],
    "Zamboanga del Sur": [
      "Pagadian City",
      "Zamboanga City",
      "Aurora",
      "Bayog",
      "Dimataling",
      "Dinas",
      "Dumalinao",
      "Dumingag",
      "Guipos",
      "Josefina",
      "Kumalarang",
      "Labangan",
      "Lakewood",
      "Lapuyan",
      "Mahayag",
      "Margosatubig",
      "Midsalip",
      "Molave",
      "Pitogo",
      "Ramon Magsaysay",
      "San Miguel",
      "San Pablo",
      "Sominot",
      "Tabina",
      "Tambulig",
      "Tigbao",
      "Tukuran",
      "Vincenzo A. Sagun",
    ],
    "Zamboanga Sibugay": [
      "Ipil",
      "Alicia",
      "Buug",
      "Diplahan",
      "Imelda",
      "Kabasalan",
      "Mabuhay",
      "Malangas",
      "Naga",
      "Olutanga",
      "Payao",
      "Roseller Lim",
      "Siay",
      "Talusan",
      "Titay",
      "Tungawan",
    ],
  },
  "Region X": {
    Bukidnon: [
      "Malaybalay City",
      "Valencia City",
      "Baungon",
      "Cabanglasan",
      "Damulog",
      "Dangcagan",
      "Don Carlos",
      "Impasugong",
      "Kadingilan",
      "Kalilangan",
      "Kibawe",
      "Kitaotao",
      "Lantapan",
      "Libona",
      "Malitbog",
      "Manolo Fortich",
      "Maramag",
      "Pangantucan",
      "Quezon",
      "San Fernando",
      "Sumilao",
      "Talakag",
    ],
    Camiguin: ["Mambajao", "Catarman", "Guinsiliban", "Mahinog", "Sagay"],
    "Lanao del Norte": [
      "Iligan City",
      "Bacolod",
      "Baloi",
      "Baroy",
      "Kapatagan",
      "Kauswagan",
      "Kolambugan",
      "Lala",
      "Linamon",
      "Magsaysay",
      "Maigo",
      "Matungao",
      "Munai",
      "Nunungan",
      "Pantao Ragat",
      "Pantar",
      "Poona Piagapo",
      "Salvador",
      "Sapad",
      "Sultan Naga Dimaporo",
      "Tagoloan",
      "Tangcal",
      "Tubod",
    ],
    "Misamis Occidental": [
      "Oroquieta City",
      "Ozamiz City",
      "Tangub City",
      "Aloran",
      "Baliangao",
      "Bonifacio",
      "Calamba",
      "Clarin",
      "Concepcion",
      "Don Victoriano Chiongbian",
      "Jimenez",
      "Lopez Jaena",
      "Panaon",
      "Plaridel",
      "Sapang Dalaga",
      "Sinacaban",
      "Tudela",
    ],
    "Misamis Oriental": [
      "Cagayan de Oro City",
      "Gingoog City",
      "El Salvador City",
      "Alubijid",
      "Balingasag",
      "Balingoan",
      "Binuangan",
      "Claveria",
      "Gitagum",
      "Initao",
      "Jasaan",
      "Kinoguitan",
      "Lagonglong",
      "Laguindingan",
      "Libertad",
      "Lugait",
      "Magsaysay",
      "Manticao",
      "Medina",
      "Naawan",
      "Opol",
      "Salay",
      "Sugbongcogon",
      "Tagoloan",
      "Talisayan",
      "Villanueva",
    ],
  },
  "Region XI": {
    "Davao de Oro": [
      "Nabunturan",
      "Compostela",
      "Laak",
      "Mabini",
      "Maco",
      "Maragusan",
      "Mawab",
      "Monkayo",
      "Montevista",
      "New Bataan",
      "Pantukan",
    ],
    "Davao del Norte": [
      "Tagum City",
      "Panabo City",
      "Samal City",
      "Asuncion",
      "Braulio E. Dujali",
      "Carmen",
      "Kapalong",
      "New Corella",
      "San Isidro",
      "Santo Tomas",
      "Talaingod",
    ],
    "Davao del Sur": [
      "Davao City",
      "Digos City",
      "Bansalan",
      "Don Marcelino",
      "Hagonoy",
      "Jose Abad Santos",
      "Kiblawan",
      "Magsaysay",
      "Malalag",
      "Malita",
      "Matanao",
      "Padada",
      "Santa Cruz",
      "Santa Maria",
      "Sarangani",
      "Sulop",
    ],
    "Davao Occidental": [
      "Malita",
      "Don Marcelino",
      "Jose Abad Santos",
      "Santa Maria",
      "Sarangani",
    ],
    "Davao Oriental": [
      "Mati City",
      "Baganga",
      "Banaybanay",
      "Boston",
      "Caraga",
      "Cateel",
      "Governor Generoso",
      "Lupon",
      "Manay",
      "San Isidro",
      "Tarragona",
    ],
  },
  "Region XII": {
    Cotabato: [
      "Kidapawan City",
      "Alamada",
      "Aleosan",
      "Antipas",
      "Arakan",
      "Banisilan",
      "Carmen",
      "Kabacan",
      "Libungan",
      "Magpet",
      "Makilala",
      "Matalam",
      "Midsayap",
      "M'lang",
      "Pigcawayan",
      "Pikit",
      "President Roxas",
      "Tulunan",
    ],
    Sarangani: [
      "Alabel",
      "Glan",
      "Kiamba",
      "Maasim",
      "Maitum",
      "Malapatan",
      "Malungon",
    ],
    "South Cotabato": [
      "Koronadal City",
      "General Santos City",
      "Banga",
      "Lake Sebu",
      "Norala",
      "Polomolok",
      "Santo Niño",
      "Surallah",
      "T'boli",
      "Tampakan",
      "Tantangan",
      "Tupi",
    ],
    "Sultan Kudarat": [
      "Isulan",
      "Tacurong City",
      "Bagumbayan",
      "Columbio",
      "Esperanza",
      "Kalamansig",
      "Lambayong",
      "Lebak",
      "Lutayan",
      "Palimbang",
      "President Quirino",
      "Senator Ninoy Aquino",
    ],
  },
  "Region XIII": {
    "Agusan del Norte": [
      "Butuan City",
      "Cabadbaran City",
      "Buenavista",
      "Carmen",
      "Jabonga",
      "Kitcharao",
      "Las Nieves",
      "Magallanes",
      "Nasipit",
      "Remedios T. Romualdez",
      "Santiago",
      "Tubay",
    ],
    "Agusan del Sur": [
      "Bayugan City",
      "Bunawan",
      "Esperanza",
      "La Paz",
      "Loreto",
      "Prosperidad",
      "Rosario",
      "San Francisco",
      "San Luis",
      "Santa Josefa",
      "Sibagat",
      "Talacogon",
      "Trento",
      "Veruela",
    ],
    "Dinagat Islands": [
      "San Jose",
      "Basilisa",
      "Cagdianao",
      "Dinagat",
      "Libjo",
      "Loreto",
      "Tubajon",
    ],
    "Surigao del Norte": [
      "Surigao City",
      "Alegria",
      "Bacuag",
      "Burgos",
      "Claver",
      "Dapa",
      "Del Carmen",
      "General Luna",
      "Gigaquit",
      "Mainit",
      "Malimono",
      "Pilar",
      "Placer",
      "San Benito",
      "San Francisco",
      "San Isidro",
      "Santa Monica",
      "Sison",
      "Socorro",
      "Tagana-an",
      "Tubod",
    ],
    "Surigao del Sur": [
      "Tandag City",
      "Bislig City",
      "Barobo",
      "Bayabas",
      "Cagwait",
      "Cantilan",
      "Carmen",
      "Carrascal",
      "Cortes",
      "Hinatuan",
      "Lanuza",
      "Lianga",
      "Lingig",
      "Madrid",
      "Marihatag",
      "San Agustin",
      "San Miguel",
      "Tagbina",
      "Tago",
    ],
  },
  BARMM: {
    Basilan: [
      "Isabela City",
      "Lamitan City",
      "Akbar",
      "Al-Barka",
      "Hadji Mohammad Ajul",
      "Hadji Muhtamad",
      "Lantawan",
      "Maluso",
      "Sumisip",
      "Tabuan-Lasa",
      "Tipo-Tipo",
      "Tuburan",
      "Ungkaya Pukan",
    ],
    "Lanao del Sur": [
      "Marawi City",
      "Bacolod-Kalawi",
      "Balabagan",
      "Balindong",
      "Bayang",
      "Binidayan",
      "Buadiposo-Buntong",
      "Bubong",
      "Bumbaran",
      "Butig",
      "Calanogas",
      "Ditsaan-Ramain",
      "Ganassi",
      "Kapai",
      "Kapatagan",
      "Lumba-Bayabao",
      "Lumbaca-Unayan",
      "Lumbatan",
      "Lumbayanague",
      "Madalum",
      "Madamba",
      "Maguing",
      "Malabang",
      "Marantao",
      "Marogong",
      "Masiu",
      "Mulondo",
      "Pagayawan",
      "Piagapo",
      "Picong",
      "Poona Bayabao",
      "Pualas",
      "Saguiaran",
      "Sultan Dumalondong",
      "Tagoloan II",
      "Tamparan",
      "Taraka",
      "Tubaran",
      "Tugaya",
      "Wao",
    ],
    "Maguindanao del Norte": [
      "Datu Odin Sinsuat",
      "Cotabato City",
      "Kabuntalan",
      "Northern Kabuntalan",
      "Sultan Kudarat",
      "Sultan Mastura",
      "Upi",
    ],
    "Maguindanao del Sur": [
      "Buluan",
      "Datu Paglas",
      "Datu Piang",
      "Datu Saudi Ampatuan",
      "Datu Unsay",
      "General Salipada K. Pendatun",
      "Guindulungan",
      "Mamasapano",
      "Mangudadatu",
      "Paglat",
      "Pandag",
      "Rajah Buayan",
      "Shariff Aguak",
      "Shariff Saydona Mustapha",
      "South Upi",
      "Sultan sa Barongis",
      "Talayan",
      "Talitay",
    ],
    Sulu: [
      "Jolo",
      "Hadji Panglima Tahil",
      "Indanan",
      "Kalingalan Caluang",
      "Lugus",
      "Luuk",
      "Maimbung",
      "Old Panamao",
      "Omar",
      "Pandami",
      "Panglima Estino",
      "Pangutaran",
      "Parang",
      "Pata",
      "Patikul",
      "Siasi",
      "Talipao",
      "Tapul",
    ],
    "Tawi-Tawi": [
      "Bongao",
      "Languyan",
      "Mapun",
      "Panglima Sugala",
      "Sapa-Sapa",
      "Sibutu",
      "Simunul",
      "Sitangkai",
      "South Ubian",
      "Tandubas",
      "Turtle Islands",
    ],
  },
};

/**
 * Get all regions as dropdown options
 */
export const getRegions = (): AddressOption[] => {
  return Object.keys(philippineAddress)
    .sort()
    .map((r) => ({ label: r, value: r }));
};

/**
 * Get provinces for a given region
 */
export const getProvinces = (region: string): AddressOption[] => {
  if (!region || !philippineAddress[region]) return [];
  return Object.keys(philippineAddress[region])
    .sort()
    .map((p) => ({ label: p, value: p }));
};

/**
 * Get cities for a given region → province
 */
export const getCities = (
  region: string,
  province: string,
): AddressOption[] => {
  if (!region || !province || !philippineAddress[region]?.[province]) return [];
  return philippineAddress[region][province]
    .sort()
    .map((c) => ({ label: c, value: c }));
};
